/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Junior Akira
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBranco = new javax.swing.JPanel();
        jpCinza = new javax.swing.JPanel();
        jpVerdeLogin = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jlUsuario = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jlCasaLogo = new javax.swing.JLabel();
        jlRiverland = new javax.swing.JLabel();
        jlCondominio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso Sistema");

        jpBranco.setBackground(new java.awt.Color(255, 255, 255));
        jpBranco.setToolTipText("");

        jpCinza.setBackground(new java.awt.Color(153, 153, 153));

        jpVerdeLogin.setBackground(new java.awt.Color(0, 153, 153));

        jlLogin.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jlLogin.setText("Login");

        javax.swing.GroupLayout jpVerdeLoginLayout = new javax.swing.GroupLayout(jpVerdeLogin);
        jpVerdeLogin.setLayout(jpVerdeLoginLayout);
        jpVerdeLoginLayout.setHorizontalGroup(
            jpVerdeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVerdeLoginLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jlLogin)
                .addGap(69, 69, 69))
        );
        jpVerdeLoginLayout.setVerticalGroup(
            jpVerdeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVerdeLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlLogin)
                .addContainerGap())
        );

        jlSenha.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jlSenha.setText("Senha");

        jlUsuario.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jlUsuario.setText("Usuário");

        jbEntrar.setBackground(new java.awt.Color(0, 102, 0));
        jbEntrar.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jbEntrar.setText("Entrar");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCinzaLayout = new javax.swing.GroupLayout(jpCinza);
        jpCinza.setLayout(jpCinzaLayout);
        jpCinzaLayout.setHorizontalGroup(
            jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCinzaLayout.createSequentialGroup()
                .addGroup(jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCinzaLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jpVerdeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCinzaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbEntrar)
                            .addGroup(jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(jpfSenha)
                                .addComponent(jlUsuario)
                                .addComponent(jlSenha)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jpCinzaLayout.setVerticalGroup(
            jpCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCinzaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jpVerdeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEntrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jlCasaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/casa128px.png"))); // NOI18N

        jlRiverland.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jlRiverland.setText("RIVERLAND");

        jlCondominio.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jlCondominio.setText("CONDOMÍNIO");

        javax.swing.GroupLayout jpBrancoLayout = new javax.swing.GroupLayout(jpBranco);
        jpBranco.setLayout(jpBrancoLayout);
        jpBrancoLayout.setHorizontalGroup(
            jpBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBrancoLayout.createSequentialGroup()
                        .addComponent(jlCasaLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCondominio)
                            .addComponent(jlRiverland)))
                    .addComponent(jpCinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpBrancoLayout.setVerticalGroup(
            jpBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBrancoLayout.createSequentialGroup()
                .addGroup(jpBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBrancoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jlCondominio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRiverland))
                    .addGroup(jpBrancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCasaLogo)))
                .addGap(19, 19, 19)
                .addComponent(jpCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
                if(jtfUsuario.getText().equalsIgnoreCase("Roberto") &&
                jpfSenha.getText().equalsIgnoreCase("2021")) //equalsIgnoreCase verifica
            //os caracteres digitado não importando se estão com letras maiúscula ou minúsculas.
        {
            JOptionPane.showMessageDialog(this, "Bem vindo ao\nCondomínio Riverland!",
                "Acesso ao sistema",JOptionPane.INFORMATION_MESSAGE); //Abre uma janela informando que
            //o sistema foi aberto.
            new JFPrincipal().setVisible(true); //Abre a janela JFPrincipal
            dispose(); //Fecha a janela JFLogin.
        }
        else
            {JOptionPane.showMessageDialog(this, "Usuário ou Senha inválidos!",
                "Meu sistema",JOptionPane.INFORMATION_MESSAGE); //Abre uma janela informando que
            //o usuário ou a senha foram digitados incorretamentes.
                jtfUsuario.setText(""); //Limpa o campo de usuário.
                jpfSenha.setText(null); //Limpa o campo de senha.
                jtfUsuario.requestFocus();} //Volta o cursor para o campo usuário.
    }//GEN-LAST:event_jbEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlCasaLogo;
    private javax.swing.JLabel jlCondominio;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlRiverland;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel jpBranco;
    private javax.swing.JPanel jpCinza;
    private javax.swing.JPanel jpVerdeLogin;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
