/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DATA.MoradoresData;
import MODEL.Moradores;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFMoradores extends javax.swing.JInternalFrame {
    private MODEL.Moradores obj;
    private DATA.MoradoresData DAO;
    private ArrayList<Moradores> listaMoradores;
    /**
     * Creates new form JIFMoradores
     */
    public JIFMoradores() {
        initComponents();
        obj = new Moradores();
        listaMoradores = new ArrayList<>();
        try {
            DAO = new MoradoresData();
        } catch (Exception ex) {
            Logger.getLogger(JIFMoradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMorador = new javax.swing.JPanel();
        jpDados = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jpContato = new javax.swing.JPanel();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        jpApartamentos = new javax.swing.JPanel();
        jcbApartamentos = new javax.swing.JComboBox<>();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlId = new javax.swing.JLabel();
        jpPesquisar = new javax.swing.JPanel();
        jtfPesquisar = new javax.swing.JTextField();
        jpMoradores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMoradores = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jbSalvar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Moradores");

        jpMorador.setBackground(new java.awt.Color(255, 255, 255));
        jpMorador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Morador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jpDados.setBackground(new java.awt.Color(255, 255, 255));
        jpDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jlNome.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jlNome.setText("Nome Completo");

        jtfNome.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtfNome.setEnabled(false);

        jlCPF.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jlCPF.setText("CPF");

        jtfCPF.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtfCPF.setEnabled(false);

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNome)
                    .addComponent(jtfCPF)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlCPF))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContato.setBackground(new java.awt.Color(255, 255, 255));
        jpContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jlEmail.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jlEmail.setText("E-mail");

        jtfEmail.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtfEmail.setEnabled(false);

        jlTelefone.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone");

        jtfTelefone.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtfTelefone.setEnabled(false);

        javax.swing.GroupLayout jpContatoLayout = new javax.swing.GroupLayout(jpContato);
        jpContato.setLayout(jpContatoLayout);
        jpContatoLayout.setHorizontalGroup(
            jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEmail)
                    .addComponent(jtfTelefone)
                    .addGroup(jpContatoLayout.createSequentialGroup()
                        .addGroup(jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEmail)
                            .addComponent(jlTelefone))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpContatoLayout.setVerticalGroup(
            jpContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpApartamentos.setBackground(new java.awt.Color(255, 255, 255));
        jpApartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apartamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jcbApartamentos.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jcbApartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        jcbApartamentos.setEnabled(false);

        javax.swing.GroupLayout jpApartamentosLayout = new javax.swing.GroupLayout(jpApartamentos);
        jpApartamentos.setLayout(jpApartamentosLayout);
        jpApartamentosLayout.setHorizontalGroup(
            jpApartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpApartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbApartamentos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpApartamentosLayout.setVerticalGroup(
            jpApartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpApartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbApartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbNovo.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/adicionar24px.png"))); // NOI18N
        jbNovo.setText("  Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/salvar24px.png"))); // NOI18N
        jbSalvar.setText("  Salvar");
        jbSalvar.setDisabledIcon(null);
        jbSalvar.setDoubleBuffered(true);
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/cancelar24px.png"))); // NOI18N
        jbCancelar.setText("  Cancelar");
        jbCancelar.setDisabledIcon(null);
        jbCancelar.setDoubleBuffered(true);
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlId.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jlId.setText("0");

        javax.swing.GroupLayout jpMoradorLayout = new javax.swing.GroupLayout(jpMorador);
        jpMorador.setLayout(jpMoradorLayout);
        jpMoradorLayout.setHorizontalGroup(
            jpMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMoradorLayout.createSequentialGroup()
                .addGroup(jpMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMoradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpApartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpMoradorLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpMoradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMoradorLayout.setVerticalGroup(
            jpMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMoradorLayout.createSequentialGroup()
                .addComponent(jlId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpApartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMoradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jpPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jtfPesquisar.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPesquisarLayout = new javax.swing.GroupLayout(jpPesquisar);
        jpPesquisar.setLayout(jpPesquisarLayout);
        jpPesquisarLayout.setHorizontalGroup(
            jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPesquisarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpPesquisarLayout.setVerticalGroup(
            jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpPesquisarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpMoradores.setBackground(new java.awt.Color(255, 255, 255));
        jpMoradores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Moradores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jtbMoradores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbMoradores.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jtbMoradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "CPF", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbMoradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMoradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbMoradores);

        jbEditar.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/editar24px.png"))); // NOI18N
        jbEditar.setText("  Editar");
        jbEditar.setDisabledIcon(null);
        jbEditar.setDoubleBuffered(true);
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbApagar.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/lixeira24px.png"))); // NOI18N
        jbApagar.setText("  Apagar");
        jbApagar.setDisabledIcon(null);
        jbApagar.setDoubleBuffered(true);
        jbApagar.setEnabled(false);
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jbSalvar1.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jbSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2 Botões/salvar24px.png"))); // NOI18N
        jbSalvar1.setText("  Salvar");
        jbSalvar1.setDisabledIcon(null);
        jbSalvar1.setDoubleBuffered(true);
        jbSalvar1.setEnabled(false);
        jbSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMoradoresLayout = new javax.swing.GroupLayout(jpMoradores);
        jpMoradores.setLayout(jpMoradoresLayout);
        jpMoradoresLayout.setHorizontalGroup(
            jpMoradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMoradoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpMoradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMoradoresLayout.createSequentialGroup()
                        .addComponent(jbEditar)
                        .addGap(28, 28, 28)
                        .addComponent(jbSalvar1)
                        .addGap(30, 30, 30)
                        .addComponent(jbApagar)
                        .addGap(37, 37, 37))))
        );
        jpMoradoresLayout.setVerticalGroup(
            jpMoradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMoradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMoradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar)
                    .addComponent(jbSalvar1)
                    .addComponent(jbApagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMorador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpMoradores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpMorador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpMoradores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jtfNome.setEnabled(true);
        jtfCPF.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfTelefone.setEnabled(true);
        jcbApartamentos.setEnabled(true);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbApagar.setEnabled(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        jtfNome.setEnabled(true);
        jtfCPF.setEnabled(true);
        jtfEmail.setEnabled(true);
        jtfTelefone.setEnabled(true);
        jcbApartamentos.setEnabled(true);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbSalvar.setEnabled(false);
        jbSalvar1.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbApagar.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    if(DAO.incluir(obj)){
                        JOptionPane.showMessageDialog(this, "Salvo com sucesso",
                                "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                        bloquearCampos();
                        limparCampos();
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro ao salvar:" +erro.getMessage(), "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        bloquearCampos();
        limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro?")==JOptionPane.YES_OPTION){
                if(DAO.excluir(Integer.parseInt(jlId.getText()))){
                    JOptionPane.showMessageDialog(this, "Excluido!");
                    bloquearCampos();
                    limparCampos();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: "+e.getMessage());
        }
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        try {
            listaMoradores = DAO.pesquisar(jtfPesquisar.getText());
            DefaultTableModel mp = (DefaultTableModel)jtbMoradores.getModel();
            mp.setNumRows(0);
            for(Moradores u: listaMoradores)
                mp.addRow(new String[]{""+u.getId(),u.getNome(),u.getCpf(),u.getTelefone()});
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar:"+e.getMessage());
        }
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtbMoradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMoradoresMouseClicked
        int linhaSelecionada = jtbMoradores.getSelectedRow();
        if(linhaSelecionada>-1){
            jlId.setText(""+listaMoradores.get(linhaSelecionada).getId());
            jtfNome.setText(listaMoradores.get(linhaSelecionada).getNome());
            jtfCPF.setText(listaMoradores.get(linhaSelecionada).getCpf());
            jtfEmail.setText(listaMoradores.get(linhaSelecionada).getEmail());
            jtfTelefone.setText(listaMoradores.get(linhaSelecionada).getTelefone());
            jcbApartamentos.setSelectedIndex(listaMoradores.get(linhaSelecionada).getApartamento());
            jbEditar.setEnabled(true);
            jbApagar.setEnabled(true);
        } else{
            jbEditar.setEnabled(false);
            jbApagar.setEnabled(false);
        }
    }//GEN-LAST:event_jtbMoradoresMouseClicked

    private void jbSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvar1ActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    if(DAO.editar(obj)){
                        JOptionPane.showMessageDialog(this, "Editado com sucesso",
                                "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                        bloquearCampos();
                        limparCampos();
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro ao salvar:" +erro.getMessage(), "Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvar1;
    private javax.swing.JComboBox<String> jcbApartamentos;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JPanel jpApartamentos;
    private javax.swing.JPanel jpContato;
    private javax.swing.JPanel jpDados;
    private javax.swing.JPanel jpMorador;
    private javax.swing.JPanel jpMoradores;
    private javax.swing.JPanel jpPesquisar;
    private javax.swing.JTable jtbMoradores;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables

    private void limparCampos(){
        jlId.setText("");
        jtfNome.setText("");
        jtfCPF.setText("");
        jtfEmail.setText("");
        jtfTelefone.setText("");
        jcbApartamentos.setSelectedIndex(0);
    }

    private void bloquearCampos(){
        jtfNome.setEnabled(false);
        jtfCPF.setEnabled(false);
        jtfEmail.setEnabled(false);
        jtfTelefone.setEnabled(false);
        jcbApartamentos.setEnabled(false);
        jbNovo.setEnabled(true);
        jbEditar.setEnabled(false);
        jbSalvar.setEnabled(false);
        jbSalvar1.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbApagar.setEnabled(false);
    }

    private boolean validarCampos(){
        String msg="";
        if (jtfNome.getText().length()<3 || jtfNome.getText().length()>50)
            msg+="\nO campo Nome precisa possuir entre 3 a 50 caracteres!";
        if (jtfCPF.getText().length()<11 || jtfCPF.getText().length()>11)
            msg+="\nO campo CPF precisa possuir 11 caracteres!";
        if (!jtfEmail.getText().contains("@") || !jtfEmail.getText().contains("."))
                msg+="\nO campo E-mail náo é válido!";
        if (jtfTelefone.getText().length()<11 || jtfTelefone.getText().length()>11)
            msg+="\nO campo Telefone precisa possuir 11 caracteres, incluindo o DDD!";
        if (jcbApartamentos.getSelectedIndex()==0)
            msg+="\nSelecione um apartamento!";
        if (msg.isEmpty()) return true;
        else JOptionPane.showMessageDialog(this, "Os campos abaixo precisam de atenção:"
                +msg, "Atenção", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    private boolean preencherObjeto() throws Exception{
        obj.setNome(jtfNome.getText());
        obj.setCpf(jtfCPF.getText());
        obj.setEmail(jtfEmail.getText());
        obj.setTelefone(jtfTelefone.getText());
        obj.setApartamento(jcbApartamentos.getSelectedIndex());
        return true;
    }

}
