/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author Roberto Junior Akira
 */
public class JIFSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFSobre
     */
    public JIFSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSobre = new javax.swing.JPanel();
        jlCondominio = new javax.swing.JLabel();
        jlRiverland = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jpVersao = new javax.swing.JPanel();
        jlSistema = new javax.swing.JLabel();
        jpCreation = new javax.swing.JPanel();
        jlRoberto = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sobre");

        jpSobre.setBackground(new java.awt.Color(255, 255, 255));
        jpSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlCondominio.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jlCondominio.setText("Condomínio");

        jlRiverland.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jlRiverland.setText("Riverland");

        jlLogo.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/casa64px.png"))); // NOI18N

        javax.swing.GroupLayout jpSobreLayout = new javax.swing.GroupLayout(jpSobre);
        jpSobre.setLayout(jpSobreLayout);
        jpSobreLayout.setHorizontalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jlLogo)
                .addGap(18, 18, 18)
                .addGroup(jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCondominio)
                    .addComponent(jlRiverland))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jpSobreLayout.setVerticalGroup(
            jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSobreLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLogo)
                    .addGroup(jpSobreLayout.createSequentialGroup()
                        .addComponent(jlCondominio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRiverland)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jpVersao.setBackground(new java.awt.Color(255, 255, 255));
        jpVersao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Version", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jlSistema.setFont(new java.awt.Font("Poor Richard", 2, 14)); // NOI18N
        jlSistema.setText("Sistema:       1 1 1 1 . 1 1 . 1 1");

        javax.swing.GroupLayout jpVersaoLayout = new javax.swing.GroupLayout(jpVersao);
        jpVersao.setLayout(jpVersaoLayout);
        jpVersaoLayout.setHorizontalGroup(
            jpVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersaoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jlSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVersaoLayout.setVerticalGroup(
            jpVersaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVersaoLayout.createSequentialGroup()
                .addComponent(jlSistema)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jpCreation.setBackground(new java.awt.Color(255, 255, 255));
        jpCreation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poor Richard", 0, 14))); // NOI18N

        jlRoberto.setFont(new java.awt.Font("Poor Richard", 2, 14)); // NOI18N
        jlRoberto.setText("Roberto  Akira  Ozaki  Junior");

        javax.swing.GroupLayout jpCreationLayout = new javax.swing.GroupLayout(jpCreation);
        jpCreation.setLayout(jpCreationLayout);
        jpCreationLayout.setHorizontalGroup(
            jpCreationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreationLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jlRoberto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCreationLayout.setVerticalGroup(
            jpCreationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCreationLayout.createSequentialGroup()
                .addComponent(jlRoberto)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpCreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCondominio;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlRiverland;
    private javax.swing.JLabel jlRoberto;
    private javax.swing.JLabel jlSistema;
    private javax.swing.JPanel jpCreation;
    private javax.swing.JPanel jpSobre;
    private javax.swing.JPanel jpVersao;
    // End of variables declaration//GEN-END:variables
}
